2018-01-20T06:42:41.351Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org2$347a7164e56d74bf523313dc659aaa5874178d23' as the object already exists)
    at /home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-01-20T06:42:41.353Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org2$347a7164e56d74bf523313dc659aaa5874178d23' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org2$347a7164e56d74bf523313dc659aaa5874178d23' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)"}$
2018-01-20T06:43:33.817Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org3$5f5fc9da3abb34ca6b2dd3de6c21a0a167b7f147' as the object already exists)
    at /home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-01-20T06:43:33.818Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org3$5f5fc9da3abb34ca6b2dd3de6c21a0a167b7f147' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'org3$5f5fc9da3abb34ca6b2dd3de6c21a0a167b7f147' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)"}$
2018-01-20T06:55:34.147Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'user4$08b887de1afac7a8d9bbe259fcb93cf16271d742' as the object already exists)
    at /home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-01-20T06:55:34.149Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'user4$08b887de1afac7a8d9bbe259fcb93cf16271d742' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'user4$08b887de1afac7a8d9bbe259fcb93cf16271d742' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/nishnik/.nvm/versions/node/v6.12.3/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)"}$
